[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
log = "0.4.33"
ratatui = "0.30.2"
reqwest = { version = "0.13.4", features = ["json"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["full"] }
tui-logger = "0.18.3"
